[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tajweed-embeddings"
version = "0.1.0"
description = "Quran Tajweed Embedding Generator"
authors = [{ name="Tarek Eldeeb" }]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
